
#
# This file is generated by 'create_byref_module.py'. Do not edit.
#
# Generated from 'python-src/Cocoa/Foundation/Foundation.byref'.
#
#
from objc import set_signature_for_selector

set_signature_for_selector("NSScanner", "scanCharactersFromSet:intoString:", "c@:@o^@")
set_signature_for_selector("NSScanner", "scanDouble:", "c@:o^d")
set_signature_for_selector("NSScanner", "scanFloat:", "c@:o^f")
set_signature_for_selector("NSScanner", "scanHexInt:", "c@:o^I")
set_signature_for_selector("NSScanner", "scanInt:", "c@:o^i")
set_signature_for_selector("NSScanner", "scanLongLong:", "c@:^oq")
set_signature_for_selector("NSScanner", "scanString:intoString:", "c@:@o^@")
set_signature_for_selector("NSScanner", "scanUpToCharactersFromSet:intoString:", "c@:@o^@")
set_signature_for_selector("NSScanner", "scanUpToString:intoString:", "c@:@o^@")
